name: Checks

on:
  - pull_request

env:
  node_version: 18

jobs:
  checkout:
    runs-on: ubuntu-latest
    - name: Checkout code
      uses: actions/checkout@v2

  # Use a Common Setup workflow
  setup_action:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup

  lint:
    needs: setup_action
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint
